// <auto-generated>
/*
 * Twitch API Swagger UI (Unofficial)
 *
 * Unofficial Swagger UI for Twitch API.  All endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.  __Features:__  * Swagger UI for all Twitch API endpoints * Schemas for _Request Query Parameters_, _Request Body_, _Response Body_ * Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc. * Response codes and examples * Generated types for TypeScript: [ts-twitch-api](https://github.com/DmitryScaletta/ts-twitch-api)  __Repository:__ [github.com/DmitryScaletta/twitch-api-swagger](https://github.com/DmitryScaletta/twitch-api-swagger)
 *
 * The version of the OpenAPI document: helix
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TwistedTaleweaver.Integration.Twitch.Helix.Client;

namespace TwistedTaleweaver.Integration.Twitch.Helix.Model
{
    /// <summary>
    /// BroadcasterSubscription
    /// </summary>
    public partial class BroadcasterSubscription : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BroadcasterSubscription" /> class.
        /// </summary>
        /// <param name="broadcasterId">An ID that identifies the broadcaster.</param>
        /// <param name="broadcasterLogin">The broadcaster’s login name.</param>
        /// <param name="broadcasterName">The broadcaster’s display name.</param>
        /// <param name="gifterId">The ID of the user that gifted the subscription to the user. Is an empty string if &#x60;is_gift&#x60; is **false**.</param>
        /// <param name="gifterLogin">The gifter’s login name. Is an empty string if &#x60;is_gift&#x60; is **false**.</param>
        /// <param name="gifterName">The gifter’s display name. Is an empty string if &#x60;is_gift&#x60; is **false**.</param>
        /// <param name="isGift">A Boolean value that determines whether the subscription is a gift subscription. Is **true** if the subscription was gifted.</param>
        /// <param name="planName">The name of the subscription.</param>
        /// <param name="tier">The type of subscription. Possible values are:      * 1000 — Tier 1 * 2000 — Tier 2 * 3000 — Tier 3</param>
        /// <param name="userId">An ID that identifies the subscribing user.</param>
        /// <param name="userName">The user’s display name.</param>
        /// <param name="userLogin">The user’s login name.</param>
        [JsonConstructor]
        public BroadcasterSubscription(string broadcasterId, string broadcasterLogin, string broadcasterName, string gifterId, string gifterLogin, string gifterName, bool isGift, string planName, TierEnum tier, string userId, string userName, string userLogin)
        {
            BroadcasterId = broadcasterId;
            BroadcasterLogin = broadcasterLogin;
            BroadcasterName = broadcasterName;
            GifterId = gifterId;
            GifterLogin = gifterLogin;
            GifterName = gifterName;
            IsGift = isGift;
            PlanName = planName;
            Tier = tier;
            UserId = userId;
            UserName = userName;
            UserLogin = userLogin;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of subscription. Possible values are:      * 1000 — Tier 1 * 2000 — Tier 2 * 3000 — Tier 3
        /// </summary>
        /// <value>The type of subscription. Possible values are:      * 1000 — Tier 1 * 2000 — Tier 2 * 3000 — Tier 3</value>
        public enum TierEnum
        {
            /// <summary>
            /// Enum _1000 for value: 1000
            /// </summary>
            _1000 = 1,

            /// <summary>
            /// Enum _2000 for value: 2000
            /// </summary>
            _2000 = 2,

            /// <summary>
            /// Enum _3000 for value: 3000
            /// </summary>
            _3000 = 3
        }

        /// <summary>
        /// Returns a <see cref="TierEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TierEnum TierEnumFromString(string value)
        {
            if (value.Equals("1000"))
                return TierEnum._1000;

            if (value.Equals("2000"))
                return TierEnum._2000;

            if (value.Equals("3000"))
                return TierEnum._3000;

            throw new NotImplementedException($"Could not convert value to type TierEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TierEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TierEnum? TierEnumFromStringOrDefault(string value)
        {
            if (value.Equals("1000"))
                return TierEnum._1000;

            if (value.Equals("2000"))
                return TierEnum._2000;

            if (value.Equals("3000"))
                return TierEnum._3000;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TierEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TierEnumToJsonValue(TierEnum value)
        {
            if (value == TierEnum._1000)
                return "1000";

            if (value == TierEnum._2000)
                return "2000";

            if (value == TierEnum._3000)
                return "3000";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The type of subscription. Possible values are:      * 1000 — Tier 1 * 2000 — Tier 2 * 3000 — Tier 3
        /// </summary>
        /// <value>The type of subscription. Possible values are:      * 1000 — Tier 1 * 2000 — Tier 2 * 3000 — Tier 3</value>
        [JsonPropertyName("tier")]
        public TierEnum Tier { get; set; }

        /// <summary>
        /// An ID that identifies the broadcaster.
        /// </summary>
        /// <value>An ID that identifies the broadcaster.</value>
        [JsonPropertyName("broadcaster_id")]
        public string BroadcasterId { get; set; }

        /// <summary>
        /// The broadcaster’s login name.
        /// </summary>
        /// <value>The broadcaster’s login name.</value>
        [JsonPropertyName("broadcaster_login")]
        public string BroadcasterLogin { get; set; }

        /// <summary>
        /// The broadcaster’s display name.
        /// </summary>
        /// <value>The broadcaster’s display name.</value>
        [JsonPropertyName("broadcaster_name")]
        public string BroadcasterName { get; set; }

        /// <summary>
        /// The ID of the user that gifted the subscription to the user. Is an empty string if &#x60;is_gift&#x60; is **false**.
        /// </summary>
        /// <value>The ID of the user that gifted the subscription to the user. Is an empty string if &#x60;is_gift&#x60; is **false**.</value>
        [JsonPropertyName("gifter_id")]
        public string GifterId { get; set; }

        /// <summary>
        /// The gifter’s login name. Is an empty string if &#x60;is_gift&#x60; is **false**.
        /// </summary>
        /// <value>The gifter’s login name. Is an empty string if &#x60;is_gift&#x60; is **false**.</value>
        [JsonPropertyName("gifter_login")]
        public string GifterLogin { get; set; }

        /// <summary>
        /// The gifter’s display name. Is an empty string if &#x60;is_gift&#x60; is **false**.
        /// </summary>
        /// <value>The gifter’s display name. Is an empty string if &#x60;is_gift&#x60; is **false**.</value>
        [JsonPropertyName("gifter_name")]
        public string GifterName { get; set; }

        /// <summary>
        /// A Boolean value that determines whether the subscription is a gift subscription. Is **true** if the subscription was gifted.
        /// </summary>
        /// <value>A Boolean value that determines whether the subscription is a gift subscription. Is **true** if the subscription was gifted.</value>
        [JsonPropertyName("is_gift")]
        public bool IsGift { get; set; }

        /// <summary>
        /// The name of the subscription.
        /// </summary>
        /// <value>The name of the subscription.</value>
        [JsonPropertyName("plan_name")]
        public string PlanName { get; set; }

        /// <summary>
        /// An ID that identifies the subscribing user.
        /// </summary>
        /// <value>An ID that identifies the subscribing user.</value>
        [JsonPropertyName("user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// The user’s display name.
        /// </summary>
        /// <value>The user’s display name.</value>
        [JsonPropertyName("user_name")]
        public string UserName { get; set; }

        /// <summary>
        /// The user’s login name.
        /// </summary>
        /// <value>The user’s login name.</value>
        [JsonPropertyName("user_login")]
        public string UserLogin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BroadcasterSubscription {\n");
            sb.Append("  BroadcasterId: ").Append(BroadcasterId).Append("\n");
            sb.Append("  BroadcasterLogin: ").Append(BroadcasterLogin).Append("\n");
            sb.Append("  BroadcasterName: ").Append(BroadcasterName).Append("\n");
            sb.Append("  GifterId: ").Append(GifterId).Append("\n");
            sb.Append("  GifterLogin: ").Append(GifterLogin).Append("\n");
            sb.Append("  GifterName: ").Append(GifterName).Append("\n");
            sb.Append("  IsGift: ").Append(IsGift).Append("\n");
            sb.Append("  PlanName: ").Append(PlanName).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  UserLogin: ").Append(UserLogin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BroadcasterSubscription" />
    /// </summary>
    public class BroadcasterSubscriptionJsonConverter : JsonConverter<BroadcasterSubscription>
    {
        /// <summary>
        /// Deserializes json to <see cref="BroadcasterSubscription" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BroadcasterSubscription Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> broadcasterId = default;
            Option<string?> broadcasterLogin = default;
            Option<string?> broadcasterName = default;
            Option<string?> gifterId = default;
            Option<string?> gifterLogin = default;
            Option<string?> gifterName = default;
            Option<bool?> isGift = default;
            Option<string?> planName = default;
            Option<BroadcasterSubscription.TierEnum?> tier = default;
            Option<string?> userId = default;
            Option<string?> userName = default;
            Option<string?> userLogin = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "broadcaster_id":
                            broadcasterId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "broadcaster_login":
                            broadcasterLogin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "broadcaster_name":
                            broadcasterName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "gifter_id":
                            gifterId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "gifter_login":
                            gifterLogin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "gifter_name":
                            gifterName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "is_gift":
                            isGift = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "plan_name":
                            planName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tier":
                            string? tierRawValue = utf8JsonReader.GetString();
                            if (tierRawValue != null)
                                tier = new Option<BroadcasterSubscription.TierEnum?>(BroadcasterSubscription.TierEnumFromStringOrDefault(tierRawValue));
                            break;
                        case "user_id":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_name":
                            userName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_login":
                            userLogin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!broadcasterId.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(broadcasterId));

            if (!broadcasterLogin.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(broadcasterLogin));

            if (!broadcasterName.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(broadcasterName));

            if (!gifterId.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(gifterId));

            if (!gifterLogin.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(gifterLogin));

            if (!gifterName.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(gifterName));

            if (!isGift.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(isGift));

            if (!planName.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(planName));

            if (!tier.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(tier));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(userId));

            if (!userName.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(userName));

            if (!userLogin.IsSet)
                throw new ArgumentException("Property is required for class BroadcasterSubscription.", nameof(userLogin));

            if (broadcasterId.IsSet && broadcasterId.Value == null)
                throw new ArgumentNullException(nameof(broadcasterId), "Property is not nullable for class BroadcasterSubscription.");

            if (broadcasterLogin.IsSet && broadcasterLogin.Value == null)
                throw new ArgumentNullException(nameof(broadcasterLogin), "Property is not nullable for class BroadcasterSubscription.");

            if (broadcasterName.IsSet && broadcasterName.Value == null)
                throw new ArgumentNullException(nameof(broadcasterName), "Property is not nullable for class BroadcasterSubscription.");

            if (gifterId.IsSet && gifterId.Value == null)
                throw new ArgumentNullException(nameof(gifterId), "Property is not nullable for class BroadcasterSubscription.");

            if (gifterLogin.IsSet && gifterLogin.Value == null)
                throw new ArgumentNullException(nameof(gifterLogin), "Property is not nullable for class BroadcasterSubscription.");

            if (gifterName.IsSet && gifterName.Value == null)
                throw new ArgumentNullException(nameof(gifterName), "Property is not nullable for class BroadcasterSubscription.");

            if (isGift.IsSet && isGift.Value == null)
                throw new ArgumentNullException(nameof(isGift), "Property is not nullable for class BroadcasterSubscription.");

            if (planName.IsSet && planName.Value == null)
                throw new ArgumentNullException(nameof(planName), "Property is not nullable for class BroadcasterSubscription.");

            if (tier.IsSet && tier.Value == null)
                throw new ArgumentNullException(nameof(tier), "Property is not nullable for class BroadcasterSubscription.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class BroadcasterSubscription.");

            if (userName.IsSet && userName.Value == null)
                throw new ArgumentNullException(nameof(userName), "Property is not nullable for class BroadcasterSubscription.");

            if (userLogin.IsSet && userLogin.Value == null)
                throw new ArgumentNullException(nameof(userLogin), "Property is not nullable for class BroadcasterSubscription.");

            return new BroadcasterSubscription(broadcasterId.Value!, broadcasterLogin.Value!, broadcasterName.Value!, gifterId.Value!, gifterLogin.Value!, gifterName.Value!, isGift.Value!.Value!, planName.Value!, tier.Value!.Value!, userId.Value!, userName.Value!, userLogin.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BroadcasterSubscription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="broadcasterSubscription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BroadcasterSubscription broadcasterSubscription, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, broadcasterSubscription, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BroadcasterSubscription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="broadcasterSubscription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BroadcasterSubscription broadcasterSubscription, JsonSerializerOptions jsonSerializerOptions)
        {
            if (broadcasterSubscription.BroadcasterId == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.BroadcasterId), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.BroadcasterLogin == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.BroadcasterLogin), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.BroadcasterName == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.BroadcasterName), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.GifterId == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.GifterId), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.GifterLogin == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.GifterLogin), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.GifterName == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.GifterName), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.PlanName == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.PlanName), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.UserId == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.UserId), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.UserName == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.UserName), "Property is required for class BroadcasterSubscription.");

            if (broadcasterSubscription.UserLogin == null)
                throw new ArgumentNullException(nameof(broadcasterSubscription.UserLogin), "Property is required for class BroadcasterSubscription.");

            writer.WriteString("broadcaster_id", broadcasterSubscription.BroadcasterId);

            writer.WriteString("broadcaster_login", broadcasterSubscription.BroadcasterLogin);

            writer.WriteString("broadcaster_name", broadcasterSubscription.BroadcasterName);

            writer.WriteString("gifter_id", broadcasterSubscription.GifterId);

            writer.WriteString("gifter_login", broadcasterSubscription.GifterLogin);

            writer.WriteString("gifter_name", broadcasterSubscription.GifterName);

            writer.WriteBoolean("is_gift", broadcasterSubscription.IsGift);

            writer.WriteString("plan_name", broadcasterSubscription.PlanName);

            var tierRawValue = BroadcasterSubscription.TierEnumToJsonValue(broadcasterSubscription.Tier);
            writer.WriteString("tier", tierRawValue);
            writer.WriteString("user_id", broadcasterSubscription.UserId);

            writer.WriteString("user_name", broadcasterSubscription.UserName);

            writer.WriteString("user_login", broadcasterSubscription.UserLogin);
        }
    }
}
