// <auto-generated>
/*
 * Twitch API Swagger UI (Unofficial)
 *
 * Unofficial Swagger UI for Twitch API.  All endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.  __Features:__  * Swagger UI for all Twitch API endpoints * Schemas for _Request Query Parameters_, _Request Body_, _Response Body_ * Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc. * Response codes and examples * Generated types for TypeScript: [ts-twitch-api](https://github.com/DmitryScaletta/ts-twitch-api)  __Repository:__ [github.com/DmitryScaletta/twitch-api-swagger](https://github.com/DmitryScaletta/twitch-api-swagger)
 *
 * The version of the OpenAPI document: helix
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TwistedTaleweaver.Integration.Twitch.Helix.Client;

namespace TwistedTaleweaver.Integration.Twitch.Helix.Model
{
    /// <summary>
    /// Describes all views-related information such as how the extension is displayed on mobile devices.
    /// </summary>
    public partial class ExtensionViews : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtensionViews" /> class.
        /// </summary>
        /// <param name="mobile">mobile</param>
        /// <param name="panel">panel</param>
        /// <param name="videoOverlay">videoOverlay</param>
        /// <param name="component">component</param>
        /// <param name="config">config</param>
        [JsonConstructor]
        public ExtensionViews(ExtensionViewsMobile mobile, ExtensionViewsPanel panel, ExtensionViewsVideoOverlay videoOverlay, ExtensionViewsComponent component, ExtensionViewsConfig config)
        {
            Mobile = mobile;
            Panel = panel;
            VideoOverlay = videoOverlay;
            Component = component;
            Config = config;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Mobile
        /// </summary>
        [JsonPropertyName("mobile")]
        public ExtensionViewsMobile Mobile { get; set; }

        /// <summary>
        /// Gets or Sets Panel
        /// </summary>
        [JsonPropertyName("panel")]
        public ExtensionViewsPanel Panel { get; set; }

        /// <summary>
        /// Gets or Sets VideoOverlay
        /// </summary>
        [JsonPropertyName("video_overlay")]
        public ExtensionViewsVideoOverlay VideoOverlay { get; set; }

        /// <summary>
        /// Gets or Sets Component
        /// </summary>
        [JsonPropertyName("component")]
        public ExtensionViewsComponent Component { get; set; }

        /// <summary>
        /// Gets or Sets Config
        /// </summary>
        [JsonPropertyName("config")]
        public ExtensionViewsConfig Config { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExtensionViews {\n");
            sb.Append("  Mobile: ").Append(Mobile).Append("\n");
            sb.Append("  Panel: ").Append(Panel).Append("\n");
            sb.Append("  VideoOverlay: ").Append(VideoOverlay).Append("\n");
            sb.Append("  Component: ").Append(Component).Append("\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExtensionViews" />
    /// </summary>
    public class ExtensionViewsJsonConverter : JsonConverter<ExtensionViews>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExtensionViews" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExtensionViews Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ExtensionViewsMobile?> mobile = default;
            Option<ExtensionViewsPanel?> panel = default;
            Option<ExtensionViewsVideoOverlay?> videoOverlay = default;
            Option<ExtensionViewsComponent?> component = default;
            Option<ExtensionViewsConfig?> config = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "mobile":
                            mobile = new Option<ExtensionViewsMobile?>(JsonSerializer.Deserialize<ExtensionViewsMobile>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "panel":
                            panel = new Option<ExtensionViewsPanel?>(JsonSerializer.Deserialize<ExtensionViewsPanel>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "video_overlay":
                            videoOverlay = new Option<ExtensionViewsVideoOverlay?>(JsonSerializer.Deserialize<ExtensionViewsVideoOverlay>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "component":
                            component = new Option<ExtensionViewsComponent?>(JsonSerializer.Deserialize<ExtensionViewsComponent>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "config":
                            config = new Option<ExtensionViewsConfig?>(JsonSerializer.Deserialize<ExtensionViewsConfig>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!mobile.IsSet)
                throw new ArgumentException("Property is required for class ExtensionViews.", nameof(mobile));

            if (!panel.IsSet)
                throw new ArgumentException("Property is required for class ExtensionViews.", nameof(panel));

            if (!videoOverlay.IsSet)
                throw new ArgumentException("Property is required for class ExtensionViews.", nameof(videoOverlay));

            if (!component.IsSet)
                throw new ArgumentException("Property is required for class ExtensionViews.", nameof(component));

            if (!config.IsSet)
                throw new ArgumentException("Property is required for class ExtensionViews.", nameof(config));

            if (mobile.IsSet && mobile.Value == null)
                throw new ArgumentNullException(nameof(mobile), "Property is not nullable for class ExtensionViews.");

            if (panel.IsSet && panel.Value == null)
                throw new ArgumentNullException(nameof(panel), "Property is not nullable for class ExtensionViews.");

            if (videoOverlay.IsSet && videoOverlay.Value == null)
                throw new ArgumentNullException(nameof(videoOverlay), "Property is not nullable for class ExtensionViews.");

            if (component.IsSet && component.Value == null)
                throw new ArgumentNullException(nameof(component), "Property is not nullable for class ExtensionViews.");

            if (config.IsSet && config.Value == null)
                throw new ArgumentNullException(nameof(config), "Property is not nullable for class ExtensionViews.");

            return new ExtensionViews(mobile.Value!, panel.Value!, videoOverlay.Value!, component.Value!, config.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ExtensionViews" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="extensionViews"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExtensionViews extensionViews, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, extensionViews, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExtensionViews" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="extensionViews"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExtensionViews extensionViews, JsonSerializerOptions jsonSerializerOptions)
        {
            if (extensionViews.Mobile == null)
                throw new ArgumentNullException(nameof(extensionViews.Mobile), "Property is required for class ExtensionViews.");

            if (extensionViews.Panel == null)
                throw new ArgumentNullException(nameof(extensionViews.Panel), "Property is required for class ExtensionViews.");

            if (extensionViews.VideoOverlay == null)
                throw new ArgumentNullException(nameof(extensionViews.VideoOverlay), "Property is required for class ExtensionViews.");

            if (extensionViews.Component == null)
                throw new ArgumentNullException(nameof(extensionViews.Component), "Property is required for class ExtensionViews.");

            if (extensionViews.Config == null)
                throw new ArgumentNullException(nameof(extensionViews.Config), "Property is required for class ExtensionViews.");

            writer.WritePropertyName("mobile");
            JsonSerializer.Serialize(writer, extensionViews.Mobile, jsonSerializerOptions);
            writer.WritePropertyName("panel");
            JsonSerializer.Serialize(writer, extensionViews.Panel, jsonSerializerOptions);
            writer.WritePropertyName("video_overlay");
            JsonSerializer.Serialize(writer, extensionViews.VideoOverlay, jsonSerializerOptions);
            writer.WritePropertyName("component");
            JsonSerializer.Serialize(writer, extensionViews.Component, jsonSerializerOptions);
            writer.WritePropertyName("config");
            JsonSerializer.Serialize(writer, extensionViews.Config, jsonSerializerOptions);
        }
    }
}
