// <auto-generated>
/*
 * Twitch API Swagger UI (Unofficial)
 *
 * Unofficial Swagger UI for Twitch API.  All endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.  __Features:__  * Swagger UI for all Twitch API endpoints * Schemas for _Request Query Parameters_, _Request Body_, _Response Body_ * Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc. * Response codes and examples * Generated types for TypeScript: [ts-twitch-api](https://github.com/DmitryScaletta/ts-twitch-api)  __Repository:__ [github.com/DmitryScaletta/twitch-api-swagger](https://github.com/DmitryScaletta/twitch-api-swagger)
 *
 * The version of the OpenAPI document: helix
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TwistedTaleweaver.Integration.Twitch.Helix.Client;

namespace TwistedTaleweaver.Integration.Twitch.Helix.Model
{
    /// <summary>
    /// GetHypeTrainEventsResponse
    /// </summary>
    public partial class GetHypeTrainEventsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetHypeTrainEventsResponse" /> class.
        /// </summary>
        /// <param name="data">The list of Hype Train events. The list is empty if the broadcaster hasn’t run a Hype Train within the last 5 days.</param>
        /// <param name="pagination">pagination</param>
        [JsonConstructor]
        public GetHypeTrainEventsResponse(List<HypeTrainEvent> data, Option<GetExtensionAnalyticsResponsePagination?> pagination = default)
        {
            Data = data;
            PaginationOption = pagination;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The list of Hype Train events. The list is empty if the broadcaster hasn’t run a Hype Train within the last 5 days.
        /// </summary>
        /// <value>The list of Hype Train events. The list is empty if the broadcaster hasn’t run a Hype Train within the last 5 days.</value>
        [JsonPropertyName("data")]
        public List<HypeTrainEvent> Data { get; set; }

        /// <summary>
        /// Used to track the state of Pagination
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GetExtensionAnalyticsResponsePagination?> PaginationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [JsonPropertyName("pagination")]
        public GetExtensionAnalyticsResponsePagination? Pagination { get { return this.PaginationOption; } set { this.PaginationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetHypeTrainEventsResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetHypeTrainEventsResponse" />
    /// </summary>
    public class GetHypeTrainEventsResponseJsonConverter : JsonConverter<GetHypeTrainEventsResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetHypeTrainEventsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetHypeTrainEventsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<HypeTrainEvent>?> data = default;
            Option<GetExtensionAnalyticsResponsePagination?> pagination = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<List<HypeTrainEvent>?>(JsonSerializer.Deserialize<List<HypeTrainEvent>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "pagination":
                            pagination = new Option<GetExtensionAnalyticsResponsePagination?>(JsonSerializer.Deserialize<GetExtensionAnalyticsResponsePagination>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class GetHypeTrainEventsResponse.", nameof(data));

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class GetHypeTrainEventsResponse.");

            if (pagination.IsSet && pagination.Value == null)
                throw new ArgumentNullException(nameof(pagination), "Property is not nullable for class GetHypeTrainEventsResponse.");

            return new GetHypeTrainEventsResponse(data.Value!, pagination);
        }

        /// <summary>
        /// Serializes a <see cref="GetHypeTrainEventsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getHypeTrainEventsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetHypeTrainEventsResponse getHypeTrainEventsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getHypeTrainEventsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetHypeTrainEventsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getHypeTrainEventsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetHypeTrainEventsResponse getHypeTrainEventsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getHypeTrainEventsResponse.Data == null)
                throw new ArgumentNullException(nameof(getHypeTrainEventsResponse.Data), "Property is required for class GetHypeTrainEventsResponse.");

            if (getHypeTrainEventsResponse.PaginationOption.IsSet && getHypeTrainEventsResponse.Pagination == null)
                throw new ArgumentNullException(nameof(getHypeTrainEventsResponse.Pagination), "Property is required for class GetHypeTrainEventsResponse.");

            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, getHypeTrainEventsResponse.Data, jsonSerializerOptions);
            if (getHypeTrainEventsResponse.PaginationOption.IsSet)
            {
                writer.WritePropertyName("pagination");
                JsonSerializer.Serialize(writer, getHypeTrainEventsResponse.Pagination, jsonSerializerOptions);
            }
        }
    }
}
