// <auto-generated>
/*
 * Twitch API Swagger UI (Unofficial)
 *
 * Unofficial Swagger UI for Twitch API.  All endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.  __Features:__  * Swagger UI for all Twitch API endpoints * Schemas for _Request Query Parameters_, _Request Body_, _Response Body_ * Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc. * Response codes and examples * Generated types for TypeScript: [ts-twitch-api](https://github.com/DmitryScaletta/ts-twitch-api)  __Repository:__ [github.com/DmitryScaletta/twitch-api-swagger](https://github.com/DmitryScaletta/twitch-api-swagger)
 *
 * The version of the OpenAPI document: helix
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TwistedTaleweaver.Integration.Twitch.Helix.Client;

namespace TwistedTaleweaver.Integration.Twitch.Helix.Model
{
    /// <summary>
    /// GetModeratedChannelsResponseDataInner
    /// </summary>
    public partial class GetModeratedChannelsResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModeratedChannelsResponseDataInner" /> class.
        /// </summary>
        /// <param name="broadcasterId">An ID that uniquely identifies the channel this user can moderate.</param>
        /// <param name="broadcasterLogin">The channel’s login name.</param>
        /// <param name="broadcasterName">The channels’ display name.</param>
        [JsonConstructor]
        public GetModeratedChannelsResponseDataInner(string broadcasterId, string broadcasterLogin, string broadcasterName)
        {
            BroadcasterId = broadcasterId;
            BroadcasterLogin = broadcasterLogin;
            BroadcasterName = broadcasterName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// An ID that uniquely identifies the channel this user can moderate.
        /// </summary>
        /// <value>An ID that uniquely identifies the channel this user can moderate.</value>
        [JsonPropertyName("broadcaster_id")]
        public string BroadcasterId { get; set; }

        /// <summary>
        /// The channel’s login name.
        /// </summary>
        /// <value>The channel’s login name.</value>
        [JsonPropertyName("broadcaster_login")]
        public string BroadcasterLogin { get; set; }

        /// <summary>
        /// The channels’ display name.
        /// </summary>
        /// <value>The channels’ display name.</value>
        [JsonPropertyName("broadcaster_name")]
        public string BroadcasterName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetModeratedChannelsResponseDataInner {\n");
            sb.Append("  BroadcasterId: ").Append(BroadcasterId).Append("\n");
            sb.Append("  BroadcasterLogin: ").Append(BroadcasterLogin).Append("\n");
            sb.Append("  BroadcasterName: ").Append(BroadcasterName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetModeratedChannelsResponseDataInner" />
    /// </summary>
    public class GetModeratedChannelsResponseDataInnerJsonConverter : JsonConverter<GetModeratedChannelsResponseDataInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetModeratedChannelsResponseDataInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetModeratedChannelsResponseDataInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> broadcasterId = default;
            Option<string?> broadcasterLogin = default;
            Option<string?> broadcasterName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "broadcaster_id":
                            broadcasterId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "broadcaster_login":
                            broadcasterLogin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "broadcaster_name":
                            broadcasterName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!broadcasterId.IsSet)
                throw new ArgumentException("Property is required for class GetModeratedChannelsResponseDataInner.", nameof(broadcasterId));

            if (!broadcasterLogin.IsSet)
                throw new ArgumentException("Property is required for class GetModeratedChannelsResponseDataInner.", nameof(broadcasterLogin));

            if (!broadcasterName.IsSet)
                throw new ArgumentException("Property is required for class GetModeratedChannelsResponseDataInner.", nameof(broadcasterName));

            if (broadcasterId.IsSet && broadcasterId.Value == null)
                throw new ArgumentNullException(nameof(broadcasterId), "Property is not nullable for class GetModeratedChannelsResponseDataInner.");

            if (broadcasterLogin.IsSet && broadcasterLogin.Value == null)
                throw new ArgumentNullException(nameof(broadcasterLogin), "Property is not nullable for class GetModeratedChannelsResponseDataInner.");

            if (broadcasterName.IsSet && broadcasterName.Value == null)
                throw new ArgumentNullException(nameof(broadcasterName), "Property is not nullable for class GetModeratedChannelsResponseDataInner.");

            return new GetModeratedChannelsResponseDataInner(broadcasterId.Value!, broadcasterLogin.Value!, broadcasterName.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetModeratedChannelsResponseDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getModeratedChannelsResponseDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetModeratedChannelsResponseDataInner getModeratedChannelsResponseDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getModeratedChannelsResponseDataInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetModeratedChannelsResponseDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getModeratedChannelsResponseDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetModeratedChannelsResponseDataInner getModeratedChannelsResponseDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getModeratedChannelsResponseDataInner.BroadcasterId == null)
                throw new ArgumentNullException(nameof(getModeratedChannelsResponseDataInner.BroadcasterId), "Property is required for class GetModeratedChannelsResponseDataInner.");

            if (getModeratedChannelsResponseDataInner.BroadcasterLogin == null)
                throw new ArgumentNullException(nameof(getModeratedChannelsResponseDataInner.BroadcasterLogin), "Property is required for class GetModeratedChannelsResponseDataInner.");

            if (getModeratedChannelsResponseDataInner.BroadcasterName == null)
                throw new ArgumentNullException(nameof(getModeratedChannelsResponseDataInner.BroadcasterName), "Property is required for class GetModeratedChannelsResponseDataInner.");

            writer.WriteString("broadcaster_id", getModeratedChannelsResponseDataInner.BroadcasterId);

            writer.WriteString("broadcaster_login", getModeratedChannelsResponseDataInner.BroadcasterLogin);

            writer.WriteString("broadcaster_name", getModeratedChannelsResponseDataInner.BroadcasterName);
        }
    }
}
