// <auto-generated>
/*
 * Twitch API Swagger UI (Unofficial)
 *
 * Unofficial Swagger UI for Twitch API.  All endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.  __Features:__  * Swagger UI for all Twitch API endpoints * Schemas for _Request Query Parameters_, _Request Body_, _Response Body_ * Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc. * Response codes and examples * Generated types for TypeScript: [ts-twitch-api](https://github.com/DmitryScaletta/ts-twitch-api)  __Repository:__ [github.com/DmitryScaletta/twitch-api-swagger](https://github.com/DmitryScaletta/twitch-api-swagger)
 *
 * The version of the OpenAPI document: helix
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TwistedTaleweaver.Integration.Twitch.Helix.Client;

namespace TwistedTaleweaver.Integration.Twitch.Helix.Model
{
    /// <summary>
    /// SnoozeNextAdResponseDataInner
    /// </summary>
    public partial class SnoozeNextAdResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SnoozeNextAdResponseDataInner" /> class.
        /// </summary>
        /// <param name="snoozeCount">The number of snoozes available for the broadcaster.</param>
        /// <param name="snoozeRefreshAt">The UTC timestamp when the broadcaster will gain an additional snooze, in RFC3339 format.</param>
        /// <param name="nextAdAt">The UTC timestamp of the broadcaster’s next scheduled ad, in RFC3339 format.</param>
        [JsonConstructor]
        public SnoozeNextAdResponseDataInner(int snoozeCount, DateTime snoozeRefreshAt, DateTime nextAdAt)
        {
            SnoozeCount = snoozeCount;
            SnoozeRefreshAt = snoozeRefreshAt;
            NextAdAt = nextAdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The number of snoozes available for the broadcaster.
        /// </summary>
        /// <value>The number of snoozes available for the broadcaster.</value>
        [JsonPropertyName("snooze_count")]
        public int SnoozeCount { get; set; }

        /// <summary>
        /// The UTC timestamp when the broadcaster will gain an additional snooze, in RFC3339 format.
        /// </summary>
        /// <value>The UTC timestamp when the broadcaster will gain an additional snooze, in RFC3339 format.</value>
        [JsonPropertyName("snooze_refresh_at")]
        public DateTime SnoozeRefreshAt { get; set; }

        /// <summary>
        /// The UTC timestamp of the broadcaster’s next scheduled ad, in RFC3339 format.
        /// </summary>
        /// <value>The UTC timestamp of the broadcaster’s next scheduled ad, in RFC3339 format.</value>
        [JsonPropertyName("next_ad_at")]
        public DateTime NextAdAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SnoozeNextAdResponseDataInner {\n");
            sb.Append("  SnoozeCount: ").Append(SnoozeCount).Append("\n");
            sb.Append("  SnoozeRefreshAt: ").Append(SnoozeRefreshAt).Append("\n");
            sb.Append("  NextAdAt: ").Append(NextAdAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SnoozeNextAdResponseDataInner" />
    /// </summary>
    public class SnoozeNextAdResponseDataInnerJsonConverter : JsonConverter<SnoozeNextAdResponseDataInner>
    {
        /// <summary>
        /// The format to use to serialize SnoozeRefreshAt
        /// </summary>
        public static string SnoozeRefreshAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize NextAdAt
        /// </summary>
        public static string NextAdAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SnoozeNextAdResponseDataInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SnoozeNextAdResponseDataInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> snoozeCount = default;
            Option<DateTime?> snoozeRefreshAt = default;
            Option<DateTime?> nextAdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "snooze_count":
                            snoozeCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "snooze_refresh_at":
                            snoozeRefreshAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "next_ad_at":
                            nextAdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!snoozeCount.IsSet)
                throw new ArgumentException("Property is required for class SnoozeNextAdResponseDataInner.", nameof(snoozeCount));

            if (!snoozeRefreshAt.IsSet)
                throw new ArgumentException("Property is required for class SnoozeNextAdResponseDataInner.", nameof(snoozeRefreshAt));

            if (!nextAdAt.IsSet)
                throw new ArgumentException("Property is required for class SnoozeNextAdResponseDataInner.", nameof(nextAdAt));

            if (snoozeCount.IsSet && snoozeCount.Value == null)
                throw new ArgumentNullException(nameof(snoozeCount), "Property is not nullable for class SnoozeNextAdResponseDataInner.");

            if (snoozeRefreshAt.IsSet && snoozeRefreshAt.Value == null)
                throw new ArgumentNullException(nameof(snoozeRefreshAt), "Property is not nullable for class SnoozeNextAdResponseDataInner.");

            if (nextAdAt.IsSet && nextAdAt.Value == null)
                throw new ArgumentNullException(nameof(nextAdAt), "Property is not nullable for class SnoozeNextAdResponseDataInner.");

            return new SnoozeNextAdResponseDataInner(snoozeCount.Value!.Value!, snoozeRefreshAt.Value!.Value!, nextAdAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SnoozeNextAdResponseDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="snoozeNextAdResponseDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SnoozeNextAdResponseDataInner snoozeNextAdResponseDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, snoozeNextAdResponseDataInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SnoozeNextAdResponseDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="snoozeNextAdResponseDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SnoozeNextAdResponseDataInner snoozeNextAdResponseDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("snooze_count", snoozeNextAdResponseDataInner.SnoozeCount);

            writer.WriteString("snooze_refresh_at", snoozeNextAdResponseDataInner.SnoozeRefreshAt.ToString(SnoozeRefreshAtFormat));

            writer.WriteString("next_ad_at", snoozeNextAdResponseDataInner.NextAdAt.ToString(NextAdAtFormat));
        }
    }
}
