services:
  kafka:
    image: bitnami/kafka:4.0.0
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: twistedtaleweaver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecretPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  twistedtaleweaver-database:
    restart: no
    image: twistedtaleweaver.database
    build:
      context: .
      dockerfile: src/TwistedTaleweaver.Database/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=twistedtaleweaver;Username=postgres;Password=SuperSecretPassword
    depends_on:
      postgres:
        condition: service_healthy

  twistedtaleweaver-bridge:
    image: twistedtaleweaver.bridge
    build:
      context: .
      dockerfile: src/TwistedTaleweaver.Bridge/Dockerfile
    environment:
     - Kafka__BootstrapServers=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env

  twistedtaleweaver:
    image: twistedtaleweaver
    build:
      context: .
      dockerfile: src/TwistedTaleweaver/Dockerfile
    environment:
     - Kafka__BootstrapServers=kafka:9092
     - DataAccess__ConnectionString=Host=postgres;Port=5432;Database=twistedtaleweaver;Username=postgres;Password=SuperSecretPassword
     - Serilog__MinimumLevel__Override__TwistedTaleweaver=Debug
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      twistedtaleweaver-database:
        condition: service_completed_successfully
    env_file:
      - .env

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      SERVER_PORT: 8443
    ports:
      - "8443:8443"
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  kafka_data:
  postgres-data:
  redis-data:
