/*
 * Twitch API Swagger UI (Unofficial)
 *
 * Unofficial Swagger UI for Twitch API.  All endpoints are generated automatically from the [twitch docs](https://dev.twitch.tv/docs/api/reference) page.  __Features:__  * Swagger UI for all Twitch API endpoints * Schemas for _Request Query Parameters_, _Request Body_, _Response Body_ * Some additional schemas like _Clip_, _ChatBadge_, _Prediction_, _Game_, _Channel_, _Video_ etc. * Response codes and examples * Generated types for TypeScript: [ts-twitch-api](https://github.com/DmitryScaletta/ts-twitch-api)  __Repository:__ [github.com/DmitryScaletta/twitch-api-swagger](https://github.com/DmitryScaletta/twitch-api-swagger)
 *
 * The version of the OpenAPI document: helix
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.DependencyInjection;
using TwistedTaleweaver.Integration.Twitch.Helix.Api;
using TwistedTaleweaver.Integration.Twitch.Helix.Model;

namespace TwistedTaleweaver.Integration.Twitch.Helix.Client
{
    /// <summary>
    /// Provides hosting configuration for TwistedTaleweaver.Integration.Twitch.Helix
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AddBlockedTermBodyJsonConverter());
            _jsonOptions.Converters.Add(new AddBlockedTermResponseJsonConverter());
            _jsonOptions.Converters.Add(new AutoModSettingsJsonConverter());
            _jsonOptions.Converters.Add(new AutoModStatusJsonConverter());
            _jsonOptions.Converters.Add(new BanUserBodyJsonConverter());
            _jsonOptions.Converters.Add(new BanUserBodyDataJsonConverter());
            _jsonOptions.Converters.Add(new BanUserResponseJsonConverter());
            _jsonOptions.Converters.Add(new BanUserResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new BannedUserJsonConverter());
            _jsonOptions.Converters.Add(new BitsLeaderboardJsonConverter());
            _jsonOptions.Converters.Add(new BlockedTermJsonConverter());
            _jsonOptions.Converters.Add(new BroadcasterSubscriptionJsonConverter());
            _jsonOptions.Converters.Add(new CategoryJsonConverter());
            _jsonOptions.Converters.Add(new ChannelJsonConverter());
            _jsonOptions.Converters.Add(new ChannelEditorJsonConverter());
            _jsonOptions.Converters.Add(new ChannelEmoteJsonConverter());
            _jsonOptions.Converters.Add(new ChannelEmoteImagesJsonConverter());
            _jsonOptions.Converters.Add(new ChannelInformationJsonConverter());
            _jsonOptions.Converters.Add(new ChannelStreamScheduleSegmentJsonConverter());
            _jsonOptions.Converters.Add(new ChannelStreamScheduleSegmentCategoryJsonConverter());
            _jsonOptions.Converters.Add(new ChannelTeamJsonConverter());
            _jsonOptions.Converters.Add(new CharityCampaignJsonConverter());
            _jsonOptions.Converters.Add(new CharityCampaignCurrentAmountJsonConverter());
            _jsonOptions.Converters.Add(new CharityCampaignDonationJsonConverter());
            _jsonOptions.Converters.Add(new CharityCampaignDonationAmountJsonConverter());
            _jsonOptions.Converters.Add(new CharityCampaignTargetAmountJsonConverter());
            _jsonOptions.Converters.Add(new ChatBadgeJsonConverter());
            _jsonOptions.Converters.Add(new ChatBadgeVersionsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ChatSettingsJsonConverter());
            _jsonOptions.Converters.Add(new ChatSettingsUpdatedJsonConverter());
            _jsonOptions.Converters.Add(new ChatterJsonConverter());
            _jsonOptions.Converters.Add(new CheckAutoModStatusBodyJsonConverter());
            _jsonOptions.Converters.Add(new CheckAutoModStatusBodyDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new CheckAutoModStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new CheckUserSubscriptionResponseJsonConverter());
            _jsonOptions.Converters.Add(new CheermoteJsonConverter());
            _jsonOptions.Converters.Add(new CheermoteImageFormatJsonConverter());
            _jsonOptions.Converters.Add(new CheermoteImageThemeJsonConverter());
            _jsonOptions.Converters.Add(new CheermoteImagesJsonConverter());
            _jsonOptions.Converters.Add(new CheermoteTiersInnerJsonConverter());
            _jsonOptions.Converters.Add(new ClipJsonConverter());
            _jsonOptions.Converters.Add(new ContentClassificationLabelJsonConverter());
            _jsonOptions.Converters.Add(new CreateChannelStreamScheduleSegmentBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateChannelStreamScheduleSegmentResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateChannelStreamScheduleSegmentResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new CreateClipResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateClipResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreateConduitsBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateConduitsResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateConduitsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreateCustomRewardsBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateCustomRewardsResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateEventSubSubscriptionBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateEventSubSubscriptionBodyTransportJsonConverter());
            _jsonOptions.Converters.Add(new CreateEventSubSubscriptionResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateExtensionSecretResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateGuestStarSessionResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreatePollBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreatePollBodyChoicesInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreatePollResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreatePredictionBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreatePredictionBodyOutcomesInnerJsonConverter());
            _jsonOptions.Converters.Add(new CreatePredictionResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateStreamMarkerBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateStreamMarkerResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreatorGoalJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardDefaultImageJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardGlobalCooldownSettingJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardImageJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardMaxPerStreamSettingJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardMaxPerUserPerStreamSettingJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardRedemptionJsonConverter());
            _jsonOptions.Converters.Add(new CustomRewardRedemptionRewardJsonConverter());
            _jsonOptions.Converters.Add(new DeleteVideosResponseJsonConverter());
            _jsonOptions.Converters.Add(new DropsEntitlementJsonConverter());
            _jsonOptions.Converters.Add(new DropsEntitlementUpdatedJsonConverter());
            _jsonOptions.Converters.Add(new EmoteJsonConverter());
            _jsonOptions.Converters.Add(new EndGuestStarSessionResponseJsonConverter());
            _jsonOptions.Converters.Add(new EndPollBodyJsonConverter());
            _jsonOptions.Converters.Add(new EndPollResponseJsonConverter());
            _jsonOptions.Converters.Add(new EndPredictionBodyJsonConverter());
            _jsonOptions.Converters.Add(new EndPredictionResponseJsonConverter());
            _jsonOptions.Converters.Add(new EventSubSubscriptionJsonConverter());
            _jsonOptions.Converters.Add(new EventSubSubscriptionTransportJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionAnalyticsJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionAnalyticsDateRangeJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionBitsProductJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionBitsProductCostJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionConfigurationSegmentJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionIconUrlsJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionLiveChannelJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionSecretJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionSecretSecretsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionTransactionJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionTransactionProductDataJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionTransactionProductDataCostJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionViewsJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionViewsComponentJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionViewsConfigJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionViewsMobileJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionViewsPanelJsonConverter());
            _jsonOptions.Converters.Add(new ExtensionViewsVideoOverlayJsonConverter());
            _jsonOptions.Converters.Add(new GameJsonConverter());
            _jsonOptions.Converters.Add(new GameAnalyticsJsonConverter());
            _jsonOptions.Converters.Add(new GetAdScheduleResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAdScheduleResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetAllStreamTagsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAllStreamTagsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetAutoModSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetBannedUsersResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetBitsLeaderboardResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetBitsLeaderboardResponseDateRangeJsonConverter());
            _jsonOptions.Converters.Add(new GetBlockedTermsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetBroadcasterSubscriptionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetBroadcasterSubscriptionsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelChatBadgesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelEditorsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelEmotesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelFollowersResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelFollowersResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelGuestStarSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelInformationResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelStreamScheduleResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelStreamScheduleResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelStreamScheduleResponseDataPaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelStreamScheduleResponseDataVacationJsonConverter());
            _jsonOptions.Converters.Add(new GetChannelTeamsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetCharityCampaignDonationsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetCharityCampaignDonationsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetCharityCampaignResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChatSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetChattersResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetCheermotesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetConduitShardsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetConduitShardsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetConduitShardsResponseDataInnerTransportJsonConverter());
            _jsonOptions.Converters.Add(new GetConduitShardsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetConduitsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetConduitsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetContentClassificationLabelsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetCreatorGoalsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetCustomRewardRedemptionResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetCustomRewardRedemptionResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetCustomRewardResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDropsEntitlementsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDropsEntitlementsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetEmoteSetsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetEventSubSubscriptionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetEventSubSubscriptionsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionAnalyticsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionAnalyticsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionBitsProductsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionConfigurationSegmentResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionLiveChannelsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionSecretsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionTransactionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetExtensionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetFollowedChannelsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetFollowedChannelsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetFollowedChannelsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetFollowedStreamsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetFollowedStreamsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetGameAnalyticsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGamesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGlobalChatBadgesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGlobalEmotesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGuestStarInvitesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGuestStarSessionResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetHypeTrainEventsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetModeratedChannelsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetModeratedChannelsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetModeratedChannelsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetModeratorsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetPollsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetPollsResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetPredictionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetReleasedExtensionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSharedChatSessionResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSharedChatSessionResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSharedChatSessionResponseDataInnerParticipantsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetShieldModeStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetShieldModeStatusResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetStreamKeyResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStreamKeyResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetStreamMarkersResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStreamTagsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStreamsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetTeamsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetTopGamesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetTopGamesResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetUnbanRequestsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetUnbanRequestsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetUserActiveExtensionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetUserActiveExtensionsResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new GetUserBlockListResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetUserChatColorResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetUserEmotesResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetUserEmotesResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetUserEmotesResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetUserExtensionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetUsersResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetVIPsResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetVideosResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetVideosResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GlobalEmoteJsonConverter());
            _jsonOptions.Converters.Add(new GuestJsonConverter());
            _jsonOptions.Converters.Add(new GuestAudioSettingsJsonConverter());
            _jsonOptions.Converters.Add(new GuestStarInviteJsonConverter());
            _jsonOptions.Converters.Add(new GuestStarSessionJsonConverter());
            _jsonOptions.Converters.Add(new GuestVideoSettingsJsonConverter());
            _jsonOptions.Converters.Add(new HypeTrainEventJsonConverter());
            _jsonOptions.Converters.Add(new HypeTrainEventEventDataJsonConverter());
            _jsonOptions.Converters.Add(new HypeTrainEventEventDataLastContributionJsonConverter());
            _jsonOptions.Converters.Add(new HypeTrainEventEventDataTopContributionsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ManageHeldAutoModMessagesBodyJsonConverter());
            _jsonOptions.Converters.Add(new ModifyChannelInformationBodyJsonConverter());
            _jsonOptions.Converters.Add(new ModifyChannelInformationBodyContentClassificationLabelsInnerJsonConverter());
            _jsonOptions.Converters.Add(new PollJsonConverter());
            _jsonOptions.Converters.Add(new PollChoicesInnerJsonConverter());
            _jsonOptions.Converters.Add(new PredictionJsonConverter());
            _jsonOptions.Converters.Add(new PredictionOutcomeJsonConverter());
            _jsonOptions.Converters.Add(new PredictionOutcomeTopPredictorsInnerJsonConverter());
            _jsonOptions.Converters.Add(new ResolveUnbanRequestsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ResolveUnbanRequestsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new SearchCategoriesResponseJsonConverter());
            _jsonOptions.Converters.Add(new SearchChannelsResponseJsonConverter());
            _jsonOptions.Converters.Add(new SendChatAnnouncementBodyJsonConverter());
            _jsonOptions.Converters.Add(new SendChatMessageBodyJsonConverter());
            _jsonOptions.Converters.Add(new SendChatMessageResponseJsonConverter());
            _jsonOptions.Converters.Add(new SendChatMessageResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new SendChatMessageResponseDataInnerDropReasonJsonConverter());
            _jsonOptions.Converters.Add(new SendExtensionChatMessageBodyJsonConverter());
            _jsonOptions.Converters.Add(new SendExtensionPubSubMessageBodyJsonConverter());
            _jsonOptions.Converters.Add(new SendWhisperBodyJsonConverter());
            _jsonOptions.Converters.Add(new SetExtensionConfigurationSegmentBodyJsonConverter());
            _jsonOptions.Converters.Add(new SetExtensionRequiredConfigurationBodyJsonConverter());
            _jsonOptions.Converters.Add(new SnoozeNextAdResponseJsonConverter());
            _jsonOptions.Converters.Add(new SnoozeNextAdResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new StartCommercialBodyJsonConverter());
            _jsonOptions.Converters.Add(new StartCommercialResponseJsonConverter());
            _jsonOptions.Converters.Add(new StartCommercialResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new StartRaidResponseJsonConverter());
            _jsonOptions.Converters.Add(new StartRaidResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new StreamJsonConverter());
            _jsonOptions.Converters.Add(new StreamMarkerCreatedJsonConverter());
            _jsonOptions.Converters.Add(new StreamMarkersJsonConverter());
            _jsonOptions.Converters.Add(new StreamMarkersMarkersInnerJsonConverter());
            _jsonOptions.Converters.Add(new StreamTagJsonConverter());
            _jsonOptions.Converters.Add(new TeamJsonConverter());
            _jsonOptions.Converters.Add(new TeamUsersInnerJsonConverter());
            _jsonOptions.Converters.Add(new UpdateAutoModSettingsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateAutoModSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateChannelGuestStarSettingsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateChannelStreamScheduleSegmentBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateChannelStreamScheduleSegmentResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateChannelStreamScheduleSegmentResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new UpdateChatSettingsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateChatSettingsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitShardsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitShardsBodyShardsInnerJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitShardsBodyShardsInnerTransportJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitShardsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitShardsResponseErrorsInnerJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateConduitsResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new UpdateCustomRewardBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateCustomRewardResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateDropsEntitlementsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateDropsEntitlementsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateExtensionBitsProductBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateExtensionBitsProductBodyCostJsonConverter());
            _jsonOptions.Converters.Add(new UpdateExtensionBitsProductResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateRedemptionStatusBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateRedemptionStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateShieldModeStatusBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateShieldModeStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateShieldModeStatusResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserExtensionsBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserExtensionsBodyDataJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserExtensionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserExtensionsResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserJsonConverter());
            _jsonOptions.Converters.Add(new UserBlockListJsonConverter());
            _jsonOptions.Converters.Add(new UserChatColorJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionComponentJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionComponentUpdateJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionOverlayJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionOverlayUpdateJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionPanelJsonConverter());
            _jsonOptions.Converters.Add(new UserExtensionPanelUpdateJsonConverter());
            _jsonOptions.Converters.Add(new UserModeratorJsonConverter());
            _jsonOptions.Converters.Add(new UserSubscriptionJsonConverter());
            _jsonOptions.Converters.Add(new UserVipJsonConverter());
            _jsonOptions.Converters.Add(new VideoJsonConverter());
            _jsonOptions.Converters.Add(new VideoMutedSegmentsInnerJsonConverter());
            _jsonOptions.Converters.Add(new WarnChatUserBodyJsonConverter());
            _jsonOptions.Converters.Add(new WarnChatUserBodyDataJsonConverter());
            _jsonOptions.Converters.Add(new WarnChatUserResponseJsonConverter());
            _jsonOptions.Converters.Add(new WarnChatUserResponseDataInnerJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<AdsApiEvents>();
            _services.AddTransient<IAdsApi, AdsApi>();
            _services.AddSingleton<AnalyticsApiEvents>();
            _services.AddTransient<IAnalyticsApi, AnalyticsApi>();
            _services.AddSingleton<BitsApiEvents>();
            _services.AddTransient<IBitsApi, BitsApi>();
            _services.AddSingleton<CCLsApiEvents>();
            _services.AddTransient<ICCLsApi, CCLsApi>();
            _services.AddSingleton<ChannelPointsApiEvents>();
            _services.AddTransient<IChannelPointsApi, ChannelPointsApi>();
            _services.AddSingleton<ChannelsApiEvents>();
            _services.AddTransient<IChannelsApi, ChannelsApi>();
            _services.AddSingleton<CharityApiEvents>();
            _services.AddTransient<ICharityApi, CharityApi>();
            _services.AddSingleton<ChatApiEvents>();
            _services.AddTransient<IChatApi, ChatApi>();
            _services.AddSingleton<ClipsApiEvents>();
            _services.AddTransient<IClipsApi, ClipsApi>();
            _services.AddSingleton<ConduitsApiEvents>();
            _services.AddTransient<IConduitsApi, ConduitsApi>();
            _services.AddSingleton<EntitlementsApiEvents>();
            _services.AddTransient<IEntitlementsApi, EntitlementsApi>();
            _services.AddSingleton<EventSubApiEvents>();
            _services.AddTransient<IEventSubApi, EventSubApi>();
            _services.AddSingleton<ExtensionsApiEvents>();
            _services.AddTransient<IExtensionsApi, ExtensionsApi>();
            _services.AddSingleton<GamesApiEvents>();
            _services.AddTransient<IGamesApi, GamesApi>();
            _services.AddSingleton<GoalsApiEvents>();
            _services.AddTransient<IGoalsApi, GoalsApi>();
            _services.AddSingleton<GuestStarApiEvents>();
            _services.AddTransient<IGuestStarApi, GuestStarApi>();
            _services.AddSingleton<HypeTrainApiEvents>();
            _services.AddTransient<IHypeTrainApi, HypeTrainApi>();
            _services.AddSingleton<ModerationApiEvents>();
            _services.AddTransient<IModerationApi, ModerationApi>();
            _services.AddSingleton<PollsApiEvents>();
            _services.AddTransient<IPollsApi, PollsApi>();
            _services.AddSingleton<PredictionsApiEvents>();
            _services.AddTransient<IPredictionsApi, PredictionsApi>();
            _services.AddSingleton<RaidsApiEvents>();
            _services.AddTransient<IRaidsApi, RaidsApi>();
            _services.AddSingleton<ScheduleApiEvents>();
            _services.AddTransient<IScheduleApi, ScheduleApi>();
            _services.AddSingleton<SearchApiEvents>();
            _services.AddTransient<ISearchApi, SearchApi>();
            _services.AddSingleton<StreamsApiEvents>();
            _services.AddTransient<IStreamsApi, StreamsApi>();
            _services.AddSingleton<SubscriptionsApiEvents>();
            _services.AddTransient<ISubscriptionsApi, SubscriptionsApi>();
            _services.AddSingleton<TagsApiEvents>();
            _services.AddTransient<ITagsApi, TagsApi>();
            _services.AddSingleton<TeamsApiEvents>();
            _services.AddTransient<ITeamsApi, TeamsApi>();
            _services.AddSingleton<UsersApiEvents>();
            _services.AddTransient<IUsersApi, UsersApi>();
            _services.AddSingleton<VideosApiEvents>();
            _services.AddTransient<IVideosApi, VideosApi>();
            _services.AddSingleton<WhispersApiEvents>();
            _services.AddTransient<IWhispersApi, WhispersApi>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BaseAddress);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAdsApi, AdsApi>(client));
            builders.Add(_services.AddHttpClient<IAnalyticsApi, AnalyticsApi>(client));
            builders.Add(_services.AddHttpClient<IBitsApi, BitsApi>(client));
            builders.Add(_services.AddHttpClient<ICCLsApi, CCLsApi>(client));
            builders.Add(_services.AddHttpClient<IChannelPointsApi, ChannelPointsApi>(client));
            builders.Add(_services.AddHttpClient<IChannelsApi, ChannelsApi>(client));
            builders.Add(_services.AddHttpClient<ICharityApi, CharityApi>(client));
            builders.Add(_services.AddHttpClient<IChatApi, ChatApi>(client));
            builders.Add(_services.AddHttpClient<IClipsApi, ClipsApi>(client));
            builders.Add(_services.AddHttpClient<IConduitsApi, ConduitsApi>(client));
            builders.Add(_services.AddHttpClient<IEntitlementsApi, EntitlementsApi>(client));
            builders.Add(_services.AddHttpClient<IEventSubApi, EventSubApi>(client));
            builders.Add(_services.AddHttpClient<IExtensionsApi, ExtensionsApi>(client));
            builders.Add(_services.AddHttpClient<IGamesApi, GamesApi>(client));
            builders.Add(_services.AddHttpClient<IGoalsApi, GoalsApi>(client));
            builders.Add(_services.AddHttpClient<IGuestStarApi, GuestStarApi>(client));
            builders.Add(_services.AddHttpClient<IHypeTrainApi, HypeTrainApi>(client));
            builders.Add(_services.AddHttpClient<IModerationApi, ModerationApi>(client));
            builders.Add(_services.AddHttpClient<IPollsApi, PollsApi>(client));
            builders.Add(_services.AddHttpClient<IPredictionsApi, PredictionsApi>(client));
            builders.Add(_services.AddHttpClient<IRaidsApi, RaidsApi>(client));
            builders.Add(_services.AddHttpClient<IScheduleApi, ScheduleApi>(client));
            builders.Add(_services.AddHttpClient<ISearchApi, SearchApi>(client));
            builders.Add(_services.AddHttpClient<IStreamsApi, StreamsApi>(client));
            builders.Add(_services.AddHttpClient<ISubscriptionsApi, SubscriptionsApi>(client));
            builders.Add(_services.AddHttpClient<ITagsApi, TagsApi>(client));
            builders.Add(_services.AddHttpClient<ITeamsApi, TeamsApi>(client));
            builders.Add(_services.AddHttpClient<IUsersApi, UsersApi>(client));
            builders.Add(_services.AddHttpClient<IVideosApi, VideosApi>(client));
            builders.Add(_services.AddHttpClient<IWhispersApi, WhispersApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
