name: .NET CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0 # Adjust based on your .NET version

    # Install dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the application
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Run tests
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
